CREATE TABLE `test_complex_nested_structures`(
  `id` string, 
  `site` string, 
  `occurred_at` string, 
  `visit_id` string, 
  `visitor_id` string, 
  `customer_number` string, 
  `customer_numbers` array<string>, 
  `type` array<string>, 
  `logged_in` boolean, 
  `uri_host` string, 
  `uri_path` string, 
  `uri_query_parameters` map<string,string>, 
  `referrer_host` string, 
  `referrer_path` string, 
  `referrer_query_parameters` map<string,string>, 
  `http_method` string, 
  `page_impression` boolean, 
  `first_in_visit` boolean, 
  `last_in_visit` boolean, 
  `page_content_category` string, 
  `product_listing` array<struct<product_name:string,product_number:string,product_position:string>>, 
  `product_listing_clicked` struct<product_name:string,product_number:string,product_position:string>, 
  `recommendation` array<struct<product_name:string,product_number:string,product_position:string>>, 
  `recommendation_clicked` struct<product_name:string,product_number:string,product_position:string>, 
  `sku` struct<sku_number:string,product_number:string,product_name:string,color:string,size:string,secondary_size:string,description:string,rating:string,availability:string,price:double,quantity:int>, 
  `search_term` string, 
  `search_number_of_results` int, 
  `search_related_search_event_id` string, 
  `search_related_product_detail_page_found` string, 
  `cart_modification_quantity` int, 
  `cart_modification_type` tinyint, 
  `purchase_scenario_step` tinyint, 
  `purchase_order_purchased_articles` array<struct<sku_number:string,product_number:string,product_name:string,color:string,size:string,secondary_size:string,description:string,rating:string,availability:string,price:double,quantity:int>>, 
  `purchase_order_number` string, 
  `purchase_order_invoice_date` string, 
  `purchase_order_invoice_time` string, 
  `purchase_order_total` double, 
  `purchase_order_shipping_costs_total` double, 
  `purchase_order_discounts_total` double, 
  `purchase_order_applied_discounts` array<string>, 
  `purchase_order_payment_type` string, 
  `purchase_order_delivery_type` string, 
  `custom_funnel_name` string, 
  `custom_funnel_step` string, 
  `traffic_source` string, 
  `ec_shop_code` string, 
  `day` string, 
  `date_id` string, 
  `created_at` string, 
  `created_by` string, 
  `year` string, 
  `month` string, 
  `month_id` string)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';
